build:
  excludeCorrectable: false

config:
  validation: true
  warningsAsErrors: true
  checkExhaustiveness: false
  # when writing own rules with new properties, exclude the property path e.g.: ['my_rule_set', '.*>.*>[my_property]']
  # excludes: []

processors:
  active: true
  exclude:
    - 'DetektProgressListener'
  # - 'KtFileCountProcessor'
  # - 'PackageCountProcessor'
  # - 'ClassCountProcessor'
  # - 'FunctionCountProcessor'
  # - 'PropertyCountProcessor'
  # - 'ProjectComplexityProcessor'
  # - 'ProjectCognitiveComplexityProcessor'
  # - 'ProjectLLOCProcessor'
  # - 'ProjectCLOCProcessor'
  # - 'ProjectLOCProcessor'
  # - 'ProjectSLOCProcessor'
  # - 'LicenseHeaderLoaderExtension'

console-reports:
  active: true
  exclude:
    - 'ProjectStatisticsReport'
    - 'ComplexityReport'
    - 'NotificationReport'
    - 'FindingsReport'
    - 'FileBasedFindingsReport'
  #  - 'LiteFindingsReport'

output-reports:
  active: true
  exclude:
    - 'MdOutputReport'
    - 'TxtOutputReport'
    # - 'XmlOutputReport'
    - 'HtmlOutputReport'
    - 'sarif'

coroutines:
  active: true
  InjectDispatcher:
    active: true
    severity: warning
    dispatcherNames:
      - 'IO'
      - 'Default'
      - 'Unconfined'
  RedundantSuspendModifier:
    active: true
    severity: warning
  SleepInsteadOfDelay:
    active: true
    severity: warning
  SuspendFunWithFlowReturnType:
    active: true
    severity: warning

empty-blocks:
  active: true
  EmptyCatchBlock:
    active: true
    severity: warning
    allowedExceptionNameRegex: '_|(ignore|expected).*'
  EmptyClassBlock:
    active: true
    severity: warning
  EmptyDefaultConstructor:
    active: true
    severity: warning
  EmptyDoWhileBlock:
    active: true
    severity: warning
  EmptyElseBlock:
    active: true
    severity: warning
  EmptyFinallyBlock:
    active: true
    severity: warning
  EmptyForBlock:
    active: true
    severity: warning
  EmptyFunctionBlock:
    active: true
    severity: warning
    ignoreOverridden: false
  EmptyIfBlock:
    active: true
    severity: warning
  EmptyInitBlock:
    active: true
    severity: warning
  EmptySecondaryConstructor:
    active: true
    severity: warning
  EmptyTryBlock:
    active: true
    severity: warning
  EmptyWhenBlock:
    active: true
    severity: warning
  EmptyWhileBlock:
    active: true
    severity: warning

exceptions:
  active: true
  ExceptionRaisedInUnexpectedLocation:
    active: true
    severity: warning
    methodNames:
      - 'equals'
      - 'finalize'
      - 'hashCode'
      - 'toString'
  InstanceOfCheckForException:
    active: true
    severity: warning
    excludes: ['**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/androidUnitTest/**', '**/androidInstrumentedTest/**', '**/jsTest/**', '**/iosTest/**']
  PrintStackTrace:
    active: true
    severity: warning
  RethrowCaughtException:
    active: true
    severity: warning
  ReturnFromFinally:
    active: true
    severity: warning
    ignoreLabeled: false
  SwallowedException:
    active: true
    severity: warning
    ignoredExceptionTypes:
      - 'InterruptedException'
      - 'MalformedURLException'
      - 'NumberFormatException'
      - 'ParseException'
    allowedExceptionNameRegex: '_|(ignore|expected).*'
  ThrowingExceptionFromFinally:
    active: true
    severity: warning
  ThrowingExceptionsWithoutMessageOrCause:
    active: true
    severity: warning
    excludes: ['**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/androidUnitTest/**', '**/androidInstrumentedTest/**', '**/jsTest/**', '**/iosTest/**']
    exceptions:
      - 'ArrayIndexOutOfBoundsException'
      - 'Exception'
      - 'IllegalArgumentException'
      - 'IllegalMonitorStateException'
      - 'IllegalStateException'
      - 'IndexOutOfBoundsException'
      - 'NullPointerException'
      - 'RuntimeException'
      - 'Throwable'
  ThrowingNewInstanceOfSameException:
    active: true
    severity: warning
  TooGenericExceptionCaught:
    active: true
    severity: warning
    excludes: ['**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/androidUnitTest/**', '**/androidInstrumentedTest/**', '**/jsTest/**', '**/iosTest/**']
    exceptionNames:
      - 'ArrayIndexOutOfBoundsException'
      - 'Error'
      - 'Exception'
      - 'IllegalMonitorStateException'
      - 'IndexOutOfBoundsException'
      - 'NullPointerException'
      - 'RuntimeException'
      - 'Throwable'
    allowedExceptionNameRegex: '_|(ignore|expected).*'
  TooGenericExceptionThrown:
    active: true
    severity: warning
    exceptionNames:
      - 'Error'
      - 'Exception'
      - 'RuntimeException'
      - 'Throwable'

naming:
  active: true
  BooleanPropertyNaming:
    active: true
    severity: warning
    allowedPattern: '^(is|has|are|should)'
  ClassNaming:
    active: true
    severity: warning
    classPattern: '[A-Z][a-zA-Z0-9]*'
  ConstructorParameterNaming:
    active: true
    severity: warning
    parameterPattern: '[a-z][A-Za-z0-9]*'
    privateParameterPattern: '[a-z][A-Za-z0-9]*'
    excludeClassPattern: '$^'
  EnumNaming:
    active: true
    severity: warning
    enumEntryPattern: '[A-Z][_a-zA-Z0-9]*'
  FunctionNaming:
    active: true
    severity: warning
    excludes: ['**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/androidUnitTest/**', '**/androidInstrumentedTest/**', '**/jsTest/**', '**/iosTest/**']
    functionPattern: '[a-z][a-zA-Z0-9]*'
    excludeClassPattern: '$^'
  FunctionParameterNaming:
    active: true
    severity: warning
    parameterPattern: '[a-z][A-Za-z0-9]*'
    excludeClassPattern: '$^'
  InvalidPackageDeclaration:
    active: true
    severity: warning
    rootPackage: ''
    requireRootInDeclaration: false
  MatchingDeclarationName:
    active: true
    severity: warning
    mustBeFirst: true
  MemberNameEqualsClassName:
    active: true
    severity: warning
    ignoreOverridden: true
  NoNameShadowing:
    active: true
    severity: warning
  NonBooleanPropertyPrefixedWithIs:
    active: true
    severity: warning
  ObjectPropertyNaming:
    active: true
    severity: warning
    constantPattern: '[A-Za-z][_A-Za-z0-9]*'
    propertyPattern: '[A-Za-z][_A-Za-z0-9]*'
    privatePropertyPattern: '(_)?[A-Za-z][_A-Za-z0-9]*'
  PackageNaming:
    active: true
    severity: warning
    packagePattern: '[a-z]+(\.[a-z][A-Za-z0-9]*)*'
  TopLevelPropertyNaming:
    active: true
    severity: warning
    constantPattern: '[A-Z][_A-Z0-9]*'
    propertyPattern: '[A-Za-z][_A-Za-z0-9]*'
    privatePropertyPattern: '_?[A-Za-z][_A-Za-z0-9]*'
  VariableNaming:
    active: true
    severity: warning
    variablePattern: '[a-z][A-Za-z0-9]*'
    privateVariablePattern: '(_)?[a-z][A-Za-z0-9]*'
    excludeClassPattern: '$^'

performance:
  active: true
  ArrayPrimitive:
    active: true
    severity: warning
  ForEachOnRange:
    active: true
    severity: warning
    excludes: ['**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/androidUnitTest/**', '**/androidInstrumentedTest/**', '**/jsTest/**', '**/iosTest/**']
  SpreadOperator:
    active: true
    severity: warning
    excludes: ['**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/androidUnitTest/**', '**/androidInstrumentedTest/**', '**/jsTest/**', '**/iosTest/**']
  UnnecessaryTemporaryInstantiation:
    active: true
    severity: warning

potential-bugs:
  active: true
  AvoidReferentialEquality:
    active: true
    severity: warning
    forbiddenTypePatterns:
      - 'kotlin.String'
  DoubleMutabilityForCollection:
    active: true
    severity: warning
    mutableTypes:
      - 'kotlin.collections.MutableList'
      - 'kotlin.collections.MutableMap'
      - 'kotlin.collections.MutableSet'
      - 'java.util.ArrayList'
      - 'java.util.LinkedHashSet'
      - 'java.util.HashSet'
      - 'java.util.LinkedHashMap'
      - 'java.util.HashMap'
  EqualsAlwaysReturnsTrueOrFalse:
    active: true
    severity: warning
  EqualsWithHashCodeExist:
    active: true
    severity: warning
  ExplicitGarbageCollectionCall:
    active: true
    severity: warning
  HasPlatformType:
    active: true
    severity: warning
  IgnoredReturnValue:
    active: true
    severity: warning
    restrictToConfig: true
    returnValueAnnotations:
      - 'CheckResult'
      - '*.CheckResult'
      - 'CheckReturnValue'
      - '*.CheckReturnValue'
    ignoreReturnValueAnnotations:
      - 'CanIgnoreReturnValue'
      - '*.CanIgnoreReturnValue'
    returnValueTypes:
      - 'kotlin.sequences.Sequence'
      - 'kotlinx.coroutines.flow.*Flow'
      - 'java.util.stream.*Stream'
    ignoreFunctionCall: []
  ImplicitDefaultLocale:
    active: true
    severity: warning
  InvalidRange:
    active: true
    severity: warning
  IteratorHasNextCallsNextMethod:
    active: true
    severity: warning
  IteratorNotThrowingNoSuchElementException:
    active: true
    severity: warning
  MapGetWithNotNullAssertionOperator:
    active: true
    severity: warning
  UnnecessaryNotNullOperator:
    active: true
    severity: warning
  UnnecessarySafeCall:
    active: true
    severity: warning
  UnreachableCatchBlock:
    active: true
    severity: warning
  UnreachableCode:
    active: true
    severity: warning
  UnsafeCallOnNullableType:
    active: true
    severity: warning
    excludes: ['**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/androidUnitTest/**', '**/androidInstrumentedTest/**', '**/jsTest/**', '**/iosTest/**']
  UnsafeCast:
    active: true
    severity: warning
  UnusedUnaryOperator:
    active: true
    severity: warning
  UselessPostfixExpression:
    active: true
    severity: warning
  WrongEqualsTypeParameter:
    active: true
    severity: warning

style:
  active: true
  DestructuringDeclarationWithTooManyEntries:
    active: true
    severity: warning
    maxDestructuringEntries: 3
  EqualsNullCall:
    active: true
    severity: warning
  ExplicitItLambdaParameter:
    active: true
    severity: warning
  ForbiddenComment:
    active: true
    severity: warning
    comments:
      - reason: 'Forbidden FIXME todo marker in comment, please fix the problem.'
        value: 'FIXME:'
      - reason: 'Forbidden STOPSHIP todo marker in comment, please address the problem before shipping the code.'
        value: 'STOPSHIP:'
      - reason: 'Forbidden TODO todo marker in comment, please do the changes.'
        value: 'TODO:'
    allowedPatterns: ''
  ForbiddenVoid:
    active: true
    severity: warning
    ignoreOverridden: false
    ignoreUsageInGenerics: false
  FunctionOnlyReturningConstant:
    active: true
    severity: warning
    ignoreOverridableFunction: true
    ignoreActualFunction: true
    excludedFunctions: []
  LoopWithTooManyJumpStatements:
    active: true
    severity: warning
    maxJumpCount: 1
  MagicNumber:
    active: true
    severity: warning
    excludes: ['**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/androidUnitTest/**', '**/androidInstrumentedTest/**', '**/jsTest/**', '**/iosTest/**', '**/*.kts']
    ignoreNumbers:
      - '-1'
      - '0'
      - '1'
      - '2'
    ignoreHashCodeFunction: true
    ignorePropertyDeclaration: false
    ignoreLocalVariableDeclaration: false
    ignoreConstantDeclaration: true
    ignoreCompanionObjectPropertyDeclaration: true
    ignoreAnnotation: false
    ignoreNamedArgument: true
    ignoreEnums: false
    ignoreRanges: false
    ignoreExtensionFunctions: true
  MaxLineLength:
    active: true
    severity: warning
    maxLineLength: 120
    excludePackageStatements: true
    excludeImportStatements: true
    excludeCommentStatements: false
    excludeRawStrings: true
  ModifierOrder:
    active: true
    severity: warning
  NestedClassesVisibility:
    active: true
    severity: warning
  NewLineAtEndOfFile:
    active: true
    severity: warning
  ObjectLiteralToLambda:
    active: true
    severity: warning
  OptionalAbstractKeyword:
    active: true
    severity: warning
  ProtectedMemberInFinalClass:
    active: true
    severity: warning
  RedundantExplicitType:
    active: true
    severity: warning
  RedundantHigherOrderMapUsage:
    active: true
    severity: warning
  ReturnCount:
    active: true
    severity: warning
    max: 2
    excludedFunctions:
      - 'equals'
    excludeLabeled: false
    excludeReturnFromLambda: true
    excludeGuardClauses: false
  SafeCast:
    active: true
    severity: warning
  SerialVersionUIDInSerializableClass:
    active: true
    severity: warning
  ThrowsCount:
    active: true
    severity: warning
    max: 2
    excludeGuardClauses: false
  UnnecessaryApply:
    active: true
    severity: warning
  UnnecessaryFilter:
    active: true
    severity: warning
  UnnecessaryInheritance:
    active: true
    severity: warning
  UnusedParameter:
    active: true
    severity: warning
    allowedNames: 'ignored|expected'
  UnusedPrivateClass:
    active: true
    severity: warning
  UnusedPrivateMember:
    active: true
    severity: warning
    allowedNames: ''
  UnusedPrivateProperty:
    active: true
    severity: warning
    allowedNames: '_|ignored|expected|serialVersionUID'
  UseAnyOrNoneInsteadOfFind:
    active: true
    severity: warning
  UseArrayLiteralsInAnnotations:
    active: true
    severity: warning
  UseCheckNotNull:
    active: true
    severity: warning
  UseCheckOrError:
    active: true
    severity: warning
  UseIsNullOrEmpty:
    active: true
    severity: warning
  UseLet:
    active: true
    severity: warning
  UseOrEmpty:
    active: true
    severity: warning
  UseRequire:
    active: true
    severity: warning
  UseRequireNotNull:
    active: true
    severity: warning
  UselessCallOnNotNull:
    active: true
    severity: warning
  UtilityClassWithPublicConstructor:
    active: true
    severity: warning
  VarCouldBeVal:
    active: true
    severity: warning
    ignoreLateinitVar: false
  WildcardImport:
    active: true
    severity: error
    excludeImports:
      - 'java.util.*'