name: Dockerfile
on: push

jobs:
  builds:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Previous tag
        env:
          VERSION: ""
        run: |
          PROP_VALUE=$(cat $GRADLE_FILE | grep "version" | cut -d'=' -f2)
          $VERSION="$PROP_VALUE"
          echo "$PROP_VALUE"

      - run: echo ${{ steps.versionManager.output.version }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: jaetan/ktor-sample:${{ steps.lastTag.outputs.tag }}