name: Linter
on: pull_request

permissions:
  checks: write

jobs:
  builds:
    env:
      REVIEWDOG_GITHUB_API_TOKEN: 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

    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          ref: ${{ github.head_ref }}

      - name: Code review
        uses: alaegin/Detekt-Action@v1.23.5
        with:
          github_token: ${{ secrets.github_token }}
          reviewdog_reporter: github-pr-review
          reviewdog_filter: nofilter