name: Linter
on: pull_request

permissions:
  checks: write

jobs:
  builds:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          ref: ${{ github.head_ref }}

      - name: Code review
        uses: alaegin/Detekt-Action@v1.23.5
        with:
          github_token: ${{ secrets.github_token }}
          reviewdog_reporter: github-pr-check
          reviewdog_filter: nofilter
          reviewdog_level: error
          fail_on_error: true